### ISSUE TITLE
Needs to fix

### ISSUE THREAD

**Issue by rsercano** [crtmneric/GetHashtags#1]
Hello thanks for the app but you need to take care of the following issues:

1. Remove `bin/Debug` and `obj/Debug` from the source code, since those are compiled files, they shouldn't be in the version control.

2. Give a licence to your project. Checkout this [website](https://choosealicense.com/), it helps :)

3. Beware that you're using some third party frameworks, and you need to check their licenses to, for if you're allowed to use them in an open source project or not. For example if you're using a project with licence **AGPL** you need to use **AGPL** yourself too. And if those third party frameworks are paid ones, you need to remove them from your "open source" project.

4. Expand your **README.MD** file, currently there're only 2 screenshots and there's no way to understand how to use your GUI ?? Should we compile it ourselves or will you do a release and prepare a setup within it like [here](https://github.com/nosqlclient/nosqlclient/releases/tag/2.1.0) ?

5. It would be nice to remove Microsoft Visual Studio Solution files as well, actually that needs to be investigated by you, in my world, we don't put intellij idea, or eclipse ide files into version control. But I don't know about .NET

6. Welcome to open source community, try to spare the word by putting referencing of your code into related websites :)

**Comment by crtmneric** [comment]
Hi there thank you for your kind explanation.

1. Removed.
2-3.Added Apache 2.0 License(https://linqtotwitter.codeplex.com/license)
4.Now it should be compiled by ide.
5.Solution files should be included for an easy compile.
6.Thank you again sir. TEACH ME MORE MASTER!

**Comment by rsercano** [comment]
And it would be really nice of you, if you could use English labels in your app, instead of Turkish, just for globalization :)
